name:                A-O-C2021
version:             0.1.0.0
github:              "dirceuBarquette/A-O-C2021"
license:             BSD3
author:              "Dirceu Barquette"
maintainer:          "dirceu.barquette@gmail.com"
copyright:           "2021 Dirceu Barquette"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dirceuBarquette/A-O-C2021#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  A-O-C2021-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - A-O-C2021

tests:
  A-O-C2021-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - A-O-C2021
